version: '2.12.2'
services:
  apiservice:
    container_name: briianmApi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
  uiservice:
    container_name: briianmFront
    build:
      context: ./WebFront
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - apiservice
